"""Trace the six paper pieces out of Chris's sketch (and the first wordmark) into point loops.

  python3 brand/lab/tools/trace.py        writes site/lib/brand/trace.mjs and a preview png in brand/lab/out/

Each piece becomes a closed loop of N points, clockwise, starting at its topmost point,
in a shared 1000-wide space. site/lib/brand/mark.mjs morphs these toward the clean mark.
"""
import json
from collections import deque
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "brand/lab"
N = 160
NAMES = ["earL", "earR", "iDot", "stem", "u", "iBody"]


def mask_of(path, kind):
    im = Image.open(path).convert("RGB")
    if kind == "sketch":
        a = np.asarray(im).astype(float)
        m = (a[..., 0] - a[..., 2]) > 40
    else:
        m = np.asarray(im.convert("L")) < 128
    # soften jpeg crumbs, keep the torn edge
    img = Image.fromarray((m * 255).astype(np.uint8)).filter(ImageFilter.GaussianBlur(1.2))
    return np.asarray(img) > 127


def components(m):
    h, w = m.shape
    lab = np.zeros((h, w), np.int32)
    comps = []
    ys, xs = np.nonzero(m)
    k = 0
    for y0, x0 in zip(ys, xs):
        if lab[y0, x0]:
            continue
        k += 1
        q = deque([(y0, x0)])
        lab[y0, x0] = k
        pts = []
        while q:
            y, x = q.popleft()
            pts.append((y, x))
            for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                ny, nx = y + dy, x + dx
                if 0 <= ny < h and 0 <= nx < w and m[ny, nx] and not lab[ny, nx]:
                    lab[ny, nx] = k
                    q.append((ny, nx))
        comps.append((len(pts), k))
    comps.sort(reverse=True)
    return lab, [k for _, k in comps[:6]]


def boundary(sub):
    """Moore-neighbour trace of the outer boundary, clockwise in image space (y down)."""
    h, w = sub.shape
    ys, xs = np.nonzero(sub)
    i = np.argmin(ys * w + xs)
    start = (ys[i], xs[i])
    dirs = [(-1, 0), (-1, 1), (0, 1), (1, 1), (1, 0), (1, -1), (0, -1), (-1, -1)]
    pts = [start]
    cur, back = start, 6
    for _ in range(200000):
        found = False
        for j in range(8):
            d = (back + 1 + j) % 8
            ny, nx = cur[0] + dirs[d][0], cur[1] + dirs[d][1]
            if 0 <= ny < h and 0 <= nx < w and sub[ny, nx]:
                back = (d + 4) % 8
                cur = (ny, nx)
                found = True
                break
        if not found or cur == start:
            break
        pts.append(cur)
    return np.array([(x, y) for y, x in pts], float)


def resample(p, n):
    p = np.vstack([p, p[:1]])
    seg = np.linalg.norm(np.diff(p, axis=0), axis=1)
    s = np.concatenate([[0], np.cumsum(seg)])
    t = np.linspace(0, s[-1], n, endpoint=False)
    x = np.interp(t, s, p[:, 0])
    y = np.interp(t, s, p[:, 1])
    q = np.stack([x, y], 1)
    # light smoothing so pixels don't stair-step
    k = np.array([1, 2, 3, 2, 1], float); k /= k.sum()
    qs = np.stack([np.convolve(np.concatenate([q[-2:, d], q[:, d], q[:2, d]]), k, "valid") for d in (0, 1)], 1)
    top = np.argmin(qs[:, 1] + qs[:, 0] * 1e-3)
    return np.roll(qs, -top, axis=0)


def trace(path, kind):
    m = mask_of(path, kind)
    lab, keep = components(m)
    loops = []
    for k in keep:
        ys, xs = np.nonzero(lab == k)
        y0, x0 = ys.min() - 2, xs.min() - 2
        sub = np.zeros((ys.max() - y0 + 3, xs.max() - x0 + 3), bool)
        sub[ys - y0, xs - x0] = True
        b = boundary(sub) + [x0, y0]
        loops.append(resample(b, N))
    allp = np.vstack(loops)
    mn, mx = allp.min(0), allp.max(0)
    s = 1000 / (mx[0] - mn[0])
    loops = [(l - mn) * s for l in loops]
    # name by position: top row (ears, dot) left to right, then bottom row left to right
    cy = [l[:, 1].mean() for l in loops]
    order = sorted(range(6), key=lambda i: cy[i])
    top = sorted(order[:3], key=lambda i: loops[i][:, 0].mean())
    bot = sorted(order[3:], key=lambda i: loops[i][:, 0].mean())
    named = dict(zip(NAMES, [loops[i] for i in top + bot]))
    return named, float((mx[1] - mn[1]) * s)


def main():
    res = {}
    for key, path, kind in (("sketch", "brand/sketch.jpg", "sketch"), ("first", "brand/yui-logo-master-bw.png", "bw")):
        named, height = trace(ROOT / path, kind)
        res[key] = {"height": round(height, 1), "pieces": {k: [[round(x, 1), round(y, 1)] for x, y in v] for k, v in named.items()}}
    (ROOT / "site/lib/brand/trace.mjs").write_text(
        "// Generated by brand/lab/tools/trace.py from brand/sketch.jpg and the first wordmark. Do not edit.\n"
        "export default " + json.dumps(res, separators=(",", ":")) + ";\n")
    (OUT / "out").mkdir(exist_ok=True)
    for key in res:
        h = int(res[key]["height"]) + 40
        im = Image.new("RGB", (1040, h), "white")
        d = ImageDraw.Draw(im)
        for name, pts in res[key]["pieces"].items():
            pts = [(x + 20, y + 20) for x, y in pts]
            d.polygon(pts, fill=(158, 97, 83))
            d.text(pts[0], name, fill="black")
        im.save(OUT / f"out/trace-{key}.png")
    print({k: v["height"] for k, v in res.items()})


main()
