// Writes spec/shapes/scenes.json: for each input, the scene the JS model
// lays out (site/lib/yl/shapes.mjs), where every part is at a few moments,
// the wrapped label lines and the plain-text description. The app's
// ShapesScene.swift is tested against this file (YuiTests/ShapesSceneTests),
// so both platforms draw the same diagram. `node gen.mjs --check` fails if
// the committed file is stale.
//   cd spec/shapes && node gen.mjs [--check]
import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "../../site/lib/yl/yl.mjs";
import { describe, frame, labelWidth, LABEL, scene, wrap } from "../../site/lib/yl/shapes.mjs";

const INPUTS = [
  ["a row with auto arrows", `shapes "How an ask reaches your phone" caption="You ask, it lands on the board."
shape@you circle You +grow
shape arrow
shape box Board +fill
shape arrow
shape pill Lane +pulse
shape arrow label=ships
shape circle Phone tone=mint +grow`],
  ["a crowded row scales down, labels wrap", `shapes "Heat pump loop"
shape blob "Outside air" tone=mute
shape arrow
shape box "Outdoor coil" tone=lavender +fill
shape arrow
shape pill Compressor +pulse
shape arrow
shape box "Indoor coil" tone=butter +fill`],
  ["placed shapes, ids, a dashed arrow, a path", `shapes "Where the time goes" w=10 h=5 caption="Most of it is thinking."
shape@think blob Thinking at=3,2.5 size=4,3 tone=lavender +fill +grow
shape@draw dot at=8,2.5 tone=mint
shape text "drawing" at=8,3.4
shape arrow from=think to=draw +dash
shape path pts=1,4.6|3,4|5,4.4|7,3.8|9,4.2 tone=mute`],
  ["move, lines between points, a shape kept on the canvas", `shapes "Where your idea is" h=4
shape text Backlog at=1.7,0.5 tone=mute
shape line at=3.35,0.2 to=3.35,3.8 tone=mute +dash
shape pill Shapes at=1.7,2.3 size=2.6 +fill move=5,2.3
shape@dot dot Live at=5,3.4 tone=mint +pulse
shape circle Edge at=10,0`],
  ["unknown kinds draw as boxes, bad connectors are dropped", `shapes w=8 h=3
shape hexagon Six
shape arrow to=nowhere
shape arrow
shape Circle Two
shape path pts=1,1
shape line`],
  ["a lone shape", `shape circle Hello +pulse`],
  ["drawing kit: a Venn, filled circles that cross blend", `shapes w=10 h=7
shape circle at=3.8,2.6 size=4 tone=accent +fill +draw
shape circle at=6.2,2.6 size=4 tone=mint +fill +draw
shape circle at=5,4.6 size=4 tone=lavender +fill +draw
shape text Yui at=5,3.5`],
  ["drawing kit: a closed path, a contour, a callout with a leader", `shapes w=10 h=6
shape contour at=4.4,3 size=7,4.8 rings=6 tone=mint +fill
shape dot Peak at=4.4,3 tone=accent
shape path pts=7,0.8|9.2,1.4|9.4,3|8,3.8|6.9,2.4 +close +fill +dash tone=butter
shape callout "Flood zone" at=8.2,5.2 to=8.3,2.6 tone=butter`],
  ["drawing kit: bent arrows, arc and bracket", `shapes w=10 h=6
shape@ask circle Ask at=5,1.2 size=1.8 +fill
shape@build circle Build at=8,4.6 size=1.8 +fill
shape arc from=ask to=build
shape arrow from=build to=ask bend=-0.3
shape arrow from=1,5.5 to=4,5.5 bend=0.2 label=bent
shape bracket from=1,3 to=1,5 label=Span`],
  ["hand drawn: +hand shapes and the three marks", `shapes w=10 h=6
shape@card box "Pricing page" at=3,1.4 size=4,1.2 +hand
shape scribble to=card
shape@word text "Ship it today" at=3,3
shape underline to=word tone=butter
shape@task pill "Fix login" at=3,4.4 size=4,0.9 +hand
shape check to=task
shape circle Round at=8,1.4 size=1.8 tone=mint +hand
shape arrow from=7.2,3 to=8.6,3.8 +hand
shape scribble at=8,5 size=2.4,1.2 tone=lavender +fill`],
];
const TIMES = [0.2, 0.9, 2, 4.3, "still"];
const r = (v) => (typeof v === "number" ? Math.round(v * 1e4) / 1e4 : Array.isArray(v) ? v.map(r) : v && typeof v === "object" ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, r(x)])) : v);

const out = INPUTS.map(([name, input]) => {
  const ops = parse(input).filter((o) => o.op === "add");
  const lone = ops[0].preset === "shape";
  const head = lone ? {} : ops[0].props;
  const members = (lone ? ops : ops.slice(1)).map((o) => ({ id: o.id, props: o.props }));
  const sc = scene(head, members);
  const k = sc.fs / (LABEL * sc.w);
  const frames = {};
  for (const t of TIMES) {
    frames[t] = frame(sc, t === "still" ? Infinity : t).map((f) => {
      const o = { i: f.i, o: f.o, s: f.s, d: f.d };
      if (f.c) o.c = f.c;
      if (f.a) { o.a = f.a; o.b = f.b; }
      return o;
    });
  }
  const labels = Object.fromEntries(sc.items.filter((it) => it.label).map((it) => [it.i, wrap(it.label, labelWidth(it, k), it.from || it.pts ? sc.fs * 0.9 : sc.fs)]));
  return r({ name, input, members, head, scene: sc, frames, labels, text: describe(sc) });
});
const json = JSON.stringify({ about: "Shapes scenes from site/lib/yl/shapes.mjs (YUI-104). Generated by gen.mjs; numbers rounded to 4 places.", scenes: out }, null, 1) + "\n";
const file = new URL("./scenes.json", import.meta.url);
if (process.argv.includes("--check")) {
  const same = readFileSync(file, "utf8") === json;
  console.log(same ? "scenes.json is current" : "scenes.json is stale: run node gen.mjs");
  process.exit(same ? 0 : 1);
}
writeFileSync(file, json);
console.log(`wrote scenes.json: ${out.length} scenes`);
