// Writes spec/map/scenes.json: for each input, the scene the JS model lays
// out (site/lib/yl/map.mjs), where every part is at a few moments and the
// plain-text description. The app's MapScene.swift is tested against this
// file (YuiTests/MapSceneTests), so both platforms draw the same map. The
// land and each area's outline go in as a hash of the path plus its length,
// to keep the file small. `node gen.mjs --check` fails if it is stale.
//   cd spec/map && node gen.mjs [--check]
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "../../site/lib/yl/yl.mjs";
import { describe, frame, scene } from "../../site/lib/yl/map.mjs";

const MONGOLS = "53,140|43,131|38.5,128.5|34.7,126.5|37.5,122.5|31,121.8|25,119.5|22.3,114|20.5,110.2|21.8,108|22.5,103|24,98|28,97|28,86|30,80|34,74|34,70|30,66|26,62|25.5,57|28,51|30,48|33,44|36,38.5|37,36|36.5,32|41,31|41.5,41.5|45,37|46,30.5|48,27|50.5,24|54,23|57,28|60,31|62,40|60,56|58,65|56,80|55,95|53,108|55,120";
const INPUTS = [
  ["the Mongol Empire, 1279", `map "The Mongol Empire, 1279" caption="24M km². The biggest land empire there has been."
area "Mongol Empire" ${MONGOLS} tone=butter
area Raided PL|HU +dash
pin@ka Karakorum 47.2,102.8 +pulse
route East ka|37.6,127 +arrow
route West ka|50.4,30.5 +arrow
route South ka|33.3,44.4 +arrow
route North ka|60,100 +arrow`],
  ["countries by alpha-3, an unknown code, a label that looks like a code", `map "Where we ship"
area "EU" FRA|DEU|ESP|XX tone=mint
area Iberia PT ESP tone=lavender
pin Lisbon 38.7,-9.1`],
  ["across the date line", `map "Bering Strait"
area RU US tone=mute
pin Anchorage 61.2,-149.9
pin Magadan 59.6,150.8
route Ferry 59.6,150.8|61.2,-149.9 +dash`],
  ["the whole world, a route through pins", `map "Around the world" fit=world caption="Three stops."
pin@ny "New York" 40.7,-74
pin@ld London 51.5,-0.1
pin@tk Tokyo 35.7,139.7 tone=mint
route "The long way" ny|ld|nowhere|tk +arrow`],
  ["center and zoom, a lone point", `map center=48.85,2.35 zoom=6
pin Paris 48.85,2.35 +pulse +grow
area "Ring" 49.2,1.8|49.2,2.9|48.5,2.9|48.5,1.8 +dash`],
  ["a lone pin", `pin Karakorum 47.2,102.8`],
  ["an empty map", `map "Nothing yet"`],
];
const TIMES = [0.2, 0.9, 2, 4.3, "still"];
const r = (v) => (typeof v === "number" ? Math.round(v * 1e4) / 1e4 : Array.isArray(v) ? v.map(r) : v && typeof v === "object" ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, r(x)])) : v);
const hash = (s) => createHash("sha256").update(s).digest("hex").slice(0, 16);

const out = INPUTS.map(([name, input]) => {
  const ops = parse(input).filter((o) => o.op === "add");
  const lone = ops[0].preset !== "map";
  const head = lone ? {} : ops[0].props;
  const members = (lone ? ops : ops.slice(1)).map((o) => ({ id: o.id, preset: o.preset, props: o.props }));
  const sc = scene(head, members);
  const items = sc.items.map(({ path, ...it }) => (path === undefined ? it : { ...it, path: { hash: hash(path), len: path.length } }));
  const frames = {};
  for (const t of TIMES) {
    frames[t] = frame(sc, t === "still" ? Infinity : t).map((f) => ({ i: f.i, o: f.o, d: f.d, s: f.s, p: f.p }));
  }
  return {
    name, input,
    scene: r({ ...sc, land: { hash: hash(sc.land), len: sc.land.length }, items }),
    frames: r(frames),
    text: describe(sc),
  };
});
const body = JSON.stringify({ note: "Generated by spec/map/gen.mjs from site/lib/yl/map.mjs. Do not edit by hand.", scenes: out }, null, 1) + "\n";
const path = new URL("./scenes.json", import.meta.url);
if (process.argv.includes("--check")) {
  let old = "";
  try { old = readFileSync(path, "utf8"); } catch {}
  if (old !== body) { console.error("spec/map/scenes.json is stale: cd spec/map && node gen.mjs"); process.exit(1); }
  console.log(`scenes.json current, ${out.length} scenes`);
} else {
  writeFileSync(path, body);
  console.log(`${out.length} scenes -> spec/map/scenes.json (${body.length} bytes)`);
}
