// Builds site/lib/yl/world.mjs, the world outline `map` draws offline, from
// Natural Earth's 110m admin 0 countries (public domain, naturalearthdata.com).
//   curl -sSLo /tmp/ne110.geojson https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson
//   node spec/map/world.gen.mjs /tmp/ne110.geojson
// Each country keeps its ISO 3166 alpha-2 code (alpha-3 as an alias), its
// name and its rings as [lon, lat] pairs at 0.1 degree, flattened.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const src = process.argv[2];
if (!src) { console.error("usage: node spec/map/world.gen.mjs ne_110m_admin_0_countries.geojson"); process.exit(2); }
const out = join(dirname(fileURLToPath(import.meta.url)), "../../site/lib/yl/world.mjs");
const d = JSON.parse(readFileSync(src, "utf8"));
const r1 = (v) => Math.round(v * 10) / 10;

const countries = {};
const a3 = {};
for (const f of d.features) {
  const p = f.properties;
  const ok = (v) => v && v !== "-99";
  const code = ok(p.ISO_A2) ? p.ISO_A2 : ok(p.ISO_A2_EH) ? p.ISO_A2_EH : p.ADM0_A3;
  const three = ok(p.ISO_A3) ? p.ISO_A3 : ok(p.ISO_A3_EH) ? p.ISO_A3_EH : p.ADM0_A3;
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  const rings = [];
  for (const poly of polys) {
    const ring = [];
    let last = null;
    for (const [x, y] of poly[0]) {
      const k = `${r1(x)},${r1(y)}`;
      if (k === last) continue;
      last = k;
      ring.push(r1(x), r1(y));
    }
    if (ring.length >= 6) rings.push(ring);
  }
  countries[code] = { name: p.NAME, rings };
  if (three && three !== code) a3[three] = code;
}
const body = `// Generated by spec/map/world.gen.mjs from Natural Earth 110m admin 0
// countries (public domain, naturalearthdata.com). Do not edit by hand.
// COUNTRIES: ISO alpha-2 code -> { name, rings }, each ring a flat list of
// lon, lat pairs at 0.1 degree. A3: alpha-3 -> alpha-2.
export const COUNTRIES = ${JSON.stringify(countries)};
export const A3 = ${JSON.stringify(a3)};
`;
writeFileSync(out, body);
console.log(`${Object.keys(countries).length} countries, ${body.length} bytes -> ${out}`);
